var firstRun = true;
var active:ColorTransform = new ColorTransform();
active.color = 0x009900;
var inactive:ColorTransform = new ColorTransform();
inactive.color = 0x66FFFF;
var hover:ColorTransform = new ColorTransform();
hover.color = 0xFFFF00;
var prev:ColorTransform = new ColorTransform();
prev.color = 0xFFFF00;
var curr:ColorTransform = new ColorTransform();
curr.color = 0xFFFF00;
var up:ColorTransform = new ColorTransform();
up.color = 0x33ff00;
var down:ColorTransform = new ColorTransform();
down.color = 0xff0000;
var select:ColorTransform = new ColorTransform();
select.color = 0x00cc00;
var notselect:ColorTransform = new ColorTransform();
notselect.color = 0x666600;
var desti;
var V = 13;
var dist:Array= new Array();
var bfdist:Array = new Array();
var sptSet:Array= new Array();
var parentt:Array= new Array();
var routerColor:Array = new Array();
var chn = new SoundChannel();
var req:URLRequest = new URLRequest("beep.mp3"); 
var snd = new Sound(req);
var leastCost;
var path:Array = new Array();
path[0]=0;

